// Code generated by ent, DO NOT EDIT.

package chatconversation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldDeletedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldUserID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldTitle, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldAPIKeyID, v))
}

// Model applies equality check predicate on the "model" field. It's identical to ModelEQ.
func Model(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldModel, v))
}

// SystemPrompt applies equality check predicate on the "system_prompt" field. It's identical to SystemPromptEQ.
func SystemPrompt(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldSystemPrompt, v))
}

// ReasoningEffort applies equality check predicate on the "reasoning_effort" field. It's identical to ReasoningEffortEQ.
func ReasoningEffort(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldReasoningEffort, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNotNull(FieldDeletedAt))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNotIn(FieldUserID, vs...))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldContainsFold(FieldTitle, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDIsNil applies the IsNil predicate on the "api_key_id" field.
func APIKeyIDIsNil() predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldIsNull(FieldAPIKeyID))
}

// APIKeyIDNotNil applies the NotNil predicate on the "api_key_id" field.
func APIKeyIDNotNil() predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNotNull(FieldAPIKeyID))
}

// ModelEQ applies the EQ predicate on the "model" field.
func ModelEQ(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldModel, v))
}

// ModelNEQ applies the NEQ predicate on the "model" field.
func ModelNEQ(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNEQ(FieldModel, v))
}

// ModelIn applies the In predicate on the "model" field.
func ModelIn(vs ...string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldIn(FieldModel, vs...))
}

// ModelNotIn applies the NotIn predicate on the "model" field.
func ModelNotIn(vs ...string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNotIn(FieldModel, vs...))
}

// ModelGT applies the GT predicate on the "model" field.
func ModelGT(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldGT(FieldModel, v))
}

// ModelGTE applies the GTE predicate on the "model" field.
func ModelGTE(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldGTE(FieldModel, v))
}

// ModelLT applies the LT predicate on the "model" field.
func ModelLT(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldLT(FieldModel, v))
}

// ModelLTE applies the LTE predicate on the "model" field.
func ModelLTE(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldLTE(FieldModel, v))
}

// ModelContains applies the Contains predicate on the "model" field.
func ModelContains(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldContains(FieldModel, v))
}

// ModelHasPrefix applies the HasPrefix predicate on the "model" field.
func ModelHasPrefix(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldHasPrefix(FieldModel, v))
}

// ModelHasSuffix applies the HasSuffix predicate on the "model" field.
func ModelHasSuffix(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldHasSuffix(FieldModel, v))
}

// ModelEqualFold applies the EqualFold predicate on the "model" field.
func ModelEqualFold(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEqualFold(FieldModel, v))
}

// ModelContainsFold applies the ContainsFold predicate on the "model" field.
func ModelContainsFold(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldContainsFold(FieldModel, v))
}

// SystemPromptEQ applies the EQ predicate on the "system_prompt" field.
func SystemPromptEQ(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldSystemPrompt, v))
}

// SystemPromptNEQ applies the NEQ predicate on the "system_prompt" field.
func SystemPromptNEQ(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNEQ(FieldSystemPrompt, v))
}

// SystemPromptIn applies the In predicate on the "system_prompt" field.
func SystemPromptIn(vs ...string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldIn(FieldSystemPrompt, vs...))
}

// SystemPromptNotIn applies the NotIn predicate on the "system_prompt" field.
func SystemPromptNotIn(vs ...string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNotIn(FieldSystemPrompt, vs...))
}

// SystemPromptGT applies the GT predicate on the "system_prompt" field.
func SystemPromptGT(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldGT(FieldSystemPrompt, v))
}

// SystemPromptGTE applies the GTE predicate on the "system_prompt" field.
func SystemPromptGTE(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldGTE(FieldSystemPrompt, v))
}

// SystemPromptLT applies the LT predicate on the "system_prompt" field.
func SystemPromptLT(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldLT(FieldSystemPrompt, v))
}

// SystemPromptLTE applies the LTE predicate on the "system_prompt" field.
func SystemPromptLTE(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldLTE(FieldSystemPrompt, v))
}

// SystemPromptContains applies the Contains predicate on the "system_prompt" field.
func SystemPromptContains(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldContains(FieldSystemPrompt, v))
}

// SystemPromptHasPrefix applies the HasPrefix predicate on the "system_prompt" field.
func SystemPromptHasPrefix(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldHasPrefix(FieldSystemPrompt, v))
}

// SystemPromptHasSuffix applies the HasSuffix predicate on the "system_prompt" field.
func SystemPromptHasSuffix(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldHasSuffix(FieldSystemPrompt, v))
}

// SystemPromptEqualFold applies the EqualFold predicate on the "system_prompt" field.
func SystemPromptEqualFold(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEqualFold(FieldSystemPrompt, v))
}

// SystemPromptContainsFold applies the ContainsFold predicate on the "system_prompt" field.
func SystemPromptContainsFold(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldContainsFold(FieldSystemPrompt, v))
}

// ReasoningEffortEQ applies the EQ predicate on the "reasoning_effort" field.
func ReasoningEffortEQ(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEQ(FieldReasoningEffort, v))
}

// ReasoningEffortNEQ applies the NEQ predicate on the "reasoning_effort" field.
func ReasoningEffortNEQ(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNEQ(FieldReasoningEffort, v))
}

// ReasoningEffortIn applies the In predicate on the "reasoning_effort" field.
func ReasoningEffortIn(vs ...string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldIn(FieldReasoningEffort, vs...))
}

// ReasoningEffortNotIn applies the NotIn predicate on the "reasoning_effort" field.
func ReasoningEffortNotIn(vs ...string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldNotIn(FieldReasoningEffort, vs...))
}

// ReasoningEffortGT applies the GT predicate on the "reasoning_effort" field.
func ReasoningEffortGT(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldGT(FieldReasoningEffort, v))
}

// ReasoningEffortGTE applies the GTE predicate on the "reasoning_effort" field.
func ReasoningEffortGTE(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldGTE(FieldReasoningEffort, v))
}

// ReasoningEffortLT applies the LT predicate on the "reasoning_effort" field.
func ReasoningEffortLT(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldLT(FieldReasoningEffort, v))
}

// ReasoningEffortLTE applies the LTE predicate on the "reasoning_effort" field.
func ReasoningEffortLTE(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldLTE(FieldReasoningEffort, v))
}

// ReasoningEffortContains applies the Contains predicate on the "reasoning_effort" field.
func ReasoningEffortContains(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldContains(FieldReasoningEffort, v))
}

// ReasoningEffortHasPrefix applies the HasPrefix predicate on the "reasoning_effort" field.
func ReasoningEffortHasPrefix(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldHasPrefix(FieldReasoningEffort, v))
}

// ReasoningEffortHasSuffix applies the HasSuffix predicate on the "reasoning_effort" field.
func ReasoningEffortHasSuffix(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldHasSuffix(FieldReasoningEffort, v))
}

// ReasoningEffortEqualFold applies the EqualFold predicate on the "reasoning_effort" field.
func ReasoningEffortEqualFold(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldEqualFold(FieldReasoningEffort, v))
}

// ReasoningEffortContainsFold applies the ContainsFold predicate on the "reasoning_effort" field.
func ReasoningEffortContainsFold(v string) predicate.ChatConversation {
	return predicate.ChatConversation(sql.FieldContainsFold(FieldReasoningEffort, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ChatConversation {
	return predicate.ChatConversation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ChatConversation {
	return predicate.ChatConversation(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.ChatConversation {
	return predicate.ChatConversation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.ChatConversation {
	return predicate.ChatConversation(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMessages applies the HasEdge predicate on the "messages" edge.
func HasMessages() predicate.ChatConversation {
	return predicate.ChatConversation(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessagesWith applies the HasEdge predicate on the "messages" edge with a given conditions (other predicates).
func HasMessagesWith(preds ...predicate.ChatMessage) predicate.ChatConversation {
	return predicate.ChatConversation(func(s *sql.Selector) {
		step := newMessagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChatConversation) predicate.ChatConversation {
	return predicate.ChatConversation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChatConversation) predicate.ChatConversation {
	return predicate.ChatConversation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChatConversation) predicate.ChatConversation {
	return predicate.ChatConversation(sql.NotPredicates(p))
}
