// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/chatconversation"
	"github.com/Wei-Shaw/sub2api/ent/chatmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ChatMessageCreate is the builder for creating a ChatMessage entity.
type ChatMessageCreate struct {
	config
	mutation *ChatMessageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatMessageCreate) SetCreatedAt(v time.Time) *ChatMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableCreatedAt(v *time.Time) *ChatMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChatMessageCreate) SetUpdatedAt(v time.Time) *ChatMessageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableUpdatedAt(v *time.Time) *ChatMessageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetConversationID sets the "conversation_id" field.
func (_c *ChatMessageCreate) SetConversationID(v int64) *ChatMessageCreate {
	_c.mutation.SetConversationID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ChatMessageCreate) SetUserID(v int64) *ChatMessageCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *ChatMessageCreate) SetRole(v string) *ChatMessageCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *ChatMessageCreate) SetContent(v string) *ChatMessageCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ChatMessageCreate) SetStatus(v string) *ChatMessageCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableStatus(v *string) *ChatMessageCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *ChatMessageCreate) SetErrorMessage(v string) *ChatMessageCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *ChatMessageCreate) SetNillableErrorMessage(v *string) *ChatMessageCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *ChatMessageCreate) SetMetadata(v map[string]interface{}) *ChatMessageCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetConversation sets the "conversation" edge to the ChatConversation entity.
func (_c *ChatMessageCreate) SetConversation(v *ChatConversation) *ChatMessageCreate {
	return _c.SetConversationID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *ChatMessageCreate) SetUser(v *User) *ChatMessageCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the ChatMessageMutation object of the builder.
func (_c *ChatMessageCreate) Mutation() *ChatMessageMutation {
	return _c.mutation
}

// Save creates the ChatMessage in the database.
func (_c *ChatMessageCreate) Save(ctx context.Context) (*ChatMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatMessageCreate) SaveX(ctx context.Context) *ChatMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatMessageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := chatmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := chatmessage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := chatmessage.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		v := chatmessage.DefaultErrorMessage
		_c.mutation.SetErrorMessage(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatMessageCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChatMessage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChatMessage.updated_at"`)}
	}
	if _, ok := _c.mutation.ConversationID(); !ok {
		return &ValidationError{Name: "conversation_id", err: errors.New(`ent: missing required field "ChatMessage.conversation_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ChatMessage.user_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "ChatMessage.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := chatmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "ChatMessage.content"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ChatMessage.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := chatmessage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		return &ValidationError{Name: "error_message", err: errors.New(`ent: missing required field "ChatMessage.error_message"`)}
	}
	if len(_c.mutation.ConversationIDs()) == 0 {
		return &ValidationError{Name: "conversation", err: errors.New(`ent: missing required edge "ChatMessage.conversation"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ChatMessage.user"`)}
	}
	return nil
}

func (_c *ChatMessageCreate) sqlSave(ctx context.Context) (*ChatMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatMessageCreate) createSpec() (*ChatMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatmessage.Table, sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chatmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(chatmessage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(chatmessage.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(chatmessage.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(chatmessage.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(chatmessage.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(chatmessage.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if nodes := _c.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.ConversationTable,
			Columns: []string{chatmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatconversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConversationID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.UserTable,
			Columns: []string{chatmessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatMessage.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatMessageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatMessageCreate) OnConflict(opts ...sql.ConflictOption) *ChatMessageUpsertOne {
	_c.conflict = opts
	return &ChatMessageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatMessageCreate) OnConflictColumns(columns ...string) *ChatMessageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatMessageUpsertOne{
		create: _c,
	}
}

type (
	// ChatMessageUpsertOne is the builder for "upsert"-ing
	//  one ChatMessage node.
	ChatMessageUpsertOne struct {
		create *ChatMessageCreate
	}

	// ChatMessageUpsert is the "OnConflict" setter.
	ChatMessageUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatMessageUpsert) SetUpdatedAt(v time.Time) *ChatMessageUpsert {
	u.Set(chatmessage.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatMessageUpsert) UpdateUpdatedAt() *ChatMessageUpsert {
	u.SetExcluded(chatmessage.FieldUpdatedAt)
	return u
}

// SetConversationID sets the "conversation_id" field.
func (u *ChatMessageUpsert) SetConversationID(v int64) *ChatMessageUpsert {
	u.Set(chatmessage.FieldConversationID, v)
	return u
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ChatMessageUpsert) UpdateConversationID() *ChatMessageUpsert {
	u.SetExcluded(chatmessage.FieldConversationID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ChatMessageUpsert) SetUserID(v int64) *ChatMessageUpsert {
	u.Set(chatmessage.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ChatMessageUpsert) UpdateUserID() *ChatMessageUpsert {
	u.SetExcluded(chatmessage.FieldUserID)
	return u
}

// SetRole sets the "role" field.
func (u *ChatMessageUpsert) SetRole(v string) *ChatMessageUpsert {
	u.Set(chatmessage.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *ChatMessageUpsert) UpdateRole() *ChatMessageUpsert {
	u.SetExcluded(chatmessage.FieldRole)
	return u
}

// SetContent sets the "content" field.
func (u *ChatMessageUpsert) SetContent(v string) *ChatMessageUpsert {
	u.Set(chatmessage.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ChatMessageUpsert) UpdateContent() *ChatMessageUpsert {
	u.SetExcluded(chatmessage.FieldContent)
	return u
}

// SetStatus sets the "status" field.
func (u *ChatMessageUpsert) SetStatus(v string) *ChatMessageUpsert {
	u.Set(chatmessage.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChatMessageUpsert) UpdateStatus() *ChatMessageUpsert {
	u.SetExcluded(chatmessage.FieldStatus)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *ChatMessageUpsert) SetErrorMessage(v string) *ChatMessageUpsert {
	u.Set(chatmessage.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ChatMessageUpsert) UpdateErrorMessage() *ChatMessageUpsert {
	u.SetExcluded(chatmessage.FieldErrorMessage)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *ChatMessageUpsert) SetMetadata(v map[string]interface{}) *ChatMessageUpsert {
	u.Set(chatmessage.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ChatMessageUpsert) UpdateMetadata() *ChatMessageUpsert {
	u.SetExcluded(chatmessage.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *ChatMessageUpsert) ClearMetadata() *ChatMessageUpsert {
	u.SetNull(chatmessage.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChatMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatMessageUpsertOne) UpdateNewValues() *ChatMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(chatmessage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatMessage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChatMessageUpsertOne) Ignore() *ChatMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatMessageUpsertOne) DoNothing() *ChatMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatMessageCreate.OnConflict
// documentation for more info.
func (u *ChatMessageUpsertOne) Update(set func(*ChatMessageUpsert)) *ChatMessageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatMessageUpsertOne) SetUpdatedAt(v time.Time) *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatMessageUpsertOne) UpdateUpdatedAt() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *ChatMessageUpsertOne) SetConversationID(v int64) *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ChatMessageUpsertOne) UpdateConversationID() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateConversationID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ChatMessageUpsertOne) SetUserID(v int64) *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ChatMessageUpsertOne) UpdateUserID() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateUserID()
	})
}

// SetRole sets the "role" field.
func (u *ChatMessageUpsertOne) SetRole(v string) *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *ChatMessageUpsertOne) UpdateRole() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateRole()
	})
}

// SetContent sets the "content" field.
func (u *ChatMessageUpsertOne) SetContent(v string) *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ChatMessageUpsertOne) UpdateContent() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateContent()
	})
}

// SetStatus sets the "status" field.
func (u *ChatMessageUpsertOne) SetStatus(v string) *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChatMessageUpsertOne) UpdateStatus() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateStatus()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *ChatMessageUpsertOne) SetErrorMessage(v string) *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ChatMessageUpsertOne) UpdateErrorMessage() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateErrorMessage()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ChatMessageUpsertOne) SetMetadata(v map[string]interface{}) *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ChatMessageUpsertOne) UpdateMetadata() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *ChatMessageUpsertOne) ClearMetadata() *ChatMessageUpsertOne {
	return u.Update(func(s *ChatMessageUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *ChatMessageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatMessageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatMessageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChatMessageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChatMessageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChatMessageCreateBulk is the builder for creating many ChatMessage entities in bulk.
type ChatMessageCreateBulk struct {
	config
	err      error
	builders []*ChatMessageCreate
	conflict []sql.ConflictOption
}

// Save creates the ChatMessage entities in the database.
func (_c *ChatMessageCreateBulk) Save(ctx context.Context) ([]*ChatMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatMessageCreateBulk) SaveX(ctx context.Context) []*ChatMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatMessage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatMessageUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatMessageCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChatMessageUpsertBulk {
	_c.conflict = opts
	return &ChatMessageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatMessage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatMessageCreateBulk) OnConflictColumns(columns ...string) *ChatMessageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatMessageUpsertBulk{
		create: _c,
	}
}

// ChatMessageUpsertBulk is the builder for "upsert"-ing
// a bulk of ChatMessage nodes.
type ChatMessageUpsertBulk struct {
	create *ChatMessageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChatMessage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatMessageUpsertBulk) UpdateNewValues() *ChatMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(chatmessage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatMessage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChatMessageUpsertBulk) Ignore() *ChatMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatMessageUpsertBulk) DoNothing() *ChatMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatMessageCreateBulk.OnConflict
// documentation for more info.
func (u *ChatMessageUpsertBulk) Update(set func(*ChatMessageUpsert)) *ChatMessageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatMessageUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatMessageUpsertBulk) SetUpdatedAt(v time.Time) *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatMessageUpsertBulk) UpdateUpdatedAt() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetConversationID sets the "conversation_id" field.
func (u *ChatMessageUpsertBulk) SetConversationID(v int64) *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetConversationID(v)
	})
}

// UpdateConversationID sets the "conversation_id" field to the value that was provided on create.
func (u *ChatMessageUpsertBulk) UpdateConversationID() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateConversationID()
	})
}

// SetUserID sets the "user_id" field.
func (u *ChatMessageUpsertBulk) SetUserID(v int64) *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ChatMessageUpsertBulk) UpdateUserID() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateUserID()
	})
}

// SetRole sets the "role" field.
func (u *ChatMessageUpsertBulk) SetRole(v string) *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *ChatMessageUpsertBulk) UpdateRole() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateRole()
	})
}

// SetContent sets the "content" field.
func (u *ChatMessageUpsertBulk) SetContent(v string) *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ChatMessageUpsertBulk) UpdateContent() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateContent()
	})
}

// SetStatus sets the "status" field.
func (u *ChatMessageUpsertBulk) SetStatus(v string) *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ChatMessageUpsertBulk) UpdateStatus() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateStatus()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *ChatMessageUpsertBulk) SetErrorMessage(v string) *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *ChatMessageUpsertBulk) UpdateErrorMessage() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateErrorMessage()
	})
}

// SetMetadata sets the "metadata" field.
func (u *ChatMessageUpsertBulk) SetMetadata(v map[string]interface{}) *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *ChatMessageUpsertBulk) UpdateMetadata() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *ChatMessageUpsertBulk) ClearMetadata() *ChatMessageUpsertBulk {
	return u.Update(func(s *ChatMessageUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *ChatMessageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChatMessageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatMessageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatMessageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
