// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/chatconversation"
	"github.com/Wei-Shaw/sub2api/ent/chatmessage"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ChatConversationCreate is the builder for creating a ChatConversation entity.
type ChatConversationCreate struct {
	config
	mutation *ChatConversationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatConversationCreate) SetCreatedAt(v time.Time) *ChatConversationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableCreatedAt(v *time.Time) *ChatConversationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChatConversationCreate) SetUpdatedAt(v time.Time) *ChatConversationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableUpdatedAt(v *time.Time) *ChatConversationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ChatConversationCreate) SetDeletedAt(v time.Time) *ChatConversationCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableDeletedAt(v *time.Time) *ChatConversationCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ChatConversationCreate) SetUserID(v int64) *ChatConversationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *ChatConversationCreate) SetTitle(v string) *ChatConversationCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableTitle(v *string) *ChatConversationCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *ChatConversationCreate) SetAPIKeyID(v int64) *ChatConversationCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableAPIKeyID(v *int64) *ChatConversationCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetModel sets the "model" field.
func (_c *ChatConversationCreate) SetModel(v string) *ChatConversationCreate {
	_c.mutation.SetModel(v)
	return _c
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableModel(v *string) *ChatConversationCreate {
	if v != nil {
		_c.SetModel(*v)
	}
	return _c
}

// SetSystemPrompt sets the "system_prompt" field.
func (_c *ChatConversationCreate) SetSystemPrompt(v string) *ChatConversationCreate {
	_c.mutation.SetSystemPrompt(v)
	return _c
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableSystemPrompt(v *string) *ChatConversationCreate {
	if v != nil {
		_c.SetSystemPrompt(*v)
	}
	return _c
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (_c *ChatConversationCreate) SetReasoningEffort(v string) *ChatConversationCreate {
	_c.mutation.SetReasoningEffort(v)
	return _c
}

// SetNillableReasoningEffort sets the "reasoning_effort" field if the given value is not nil.
func (_c *ChatConversationCreate) SetNillableReasoningEffort(v *string) *ChatConversationCreate {
	if v != nil {
		_c.SetReasoningEffort(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *ChatConversationCreate) SetUser(v *User) *ChatConversationCreate {
	return _c.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *ChatConversationCreate) SetAPIKey(v *APIKey) *ChatConversationCreate {
	return _c.SetAPIKeyID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the ChatMessage entity by IDs.
func (_c *ChatConversationCreate) AddMessageIDs(ids ...int64) *ChatConversationCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the ChatMessage entity.
func (_c *ChatConversationCreate) AddMessages(v ...*ChatMessage) *ChatConversationCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the ChatConversationMutation object of the builder.
func (_c *ChatConversationCreate) Mutation() *ChatConversationMutation {
	return _c.mutation
}

// Save creates the ChatConversation in the database.
func (_c *ChatConversationCreate) Save(ctx context.Context) (*ChatConversation, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatConversationCreate) SaveX(ctx context.Context) *ChatConversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatConversationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatConversationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatConversationCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if chatconversation.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized chatconversation.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := chatconversation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if chatconversation.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized chatconversation.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := chatconversation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := chatconversation.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Model(); !ok {
		v := chatconversation.DefaultModel
		_c.mutation.SetModel(v)
	}
	if _, ok := _c.mutation.SystemPrompt(); !ok {
		v := chatconversation.DefaultSystemPrompt
		_c.mutation.SetSystemPrompt(v)
	}
	if _, ok := _c.mutation.ReasoningEffort(); !ok {
		v := chatconversation.DefaultReasoningEffort
		_c.mutation.SetReasoningEffort(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatConversationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChatConversation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChatConversation.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ChatConversation.user_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "ChatConversation.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := chatconversation.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Model(); !ok {
		return &ValidationError{Name: "model", err: errors.New(`ent: missing required field "ChatConversation.model"`)}
	}
	if v, ok := _c.mutation.Model(); ok {
		if err := chatconversation.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SystemPrompt(); !ok {
		return &ValidationError{Name: "system_prompt", err: errors.New(`ent: missing required field "ChatConversation.system_prompt"`)}
	}
	if _, ok := _c.mutation.ReasoningEffort(); !ok {
		return &ValidationError{Name: "reasoning_effort", err: errors.New(`ent: missing required field "ChatConversation.reasoning_effort"`)}
	}
	if v, ok := _c.mutation.ReasoningEffort(); ok {
		if err := chatconversation.ReasoningEffortValidator(v); err != nil {
			return &ValidationError{Name: "reasoning_effort", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.reasoning_effort": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "ChatConversation.user"`)}
	}
	return nil
}

func (_c *ChatConversationCreate) sqlSave(ctx context.Context) (*ChatConversation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatConversationCreate) createSpec() (*ChatConversation, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatConversation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatconversation.Table, sqlgraph.NewFieldSpec(chatconversation.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chatconversation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(chatconversation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(chatconversation.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(chatconversation.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Model(); ok {
		_spec.SetField(chatconversation.FieldModel, field.TypeString, value)
		_node.Model = value
	}
	if value, ok := _c.mutation.SystemPrompt(); ok {
		_spec.SetField(chatconversation.FieldSystemPrompt, field.TypeString, value)
		_node.SystemPrompt = value
	}
	if value, ok := _c.mutation.ReasoningEffort(); ok {
		_spec.SetField(chatconversation.FieldReasoningEffort, field.TypeString, value)
		_node.ReasoningEffort = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatconversation.UserTable,
			Columns: []string{chatconversation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatconversation.APIKeyTable,
			Columns: []string{chatconversation.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatconversation.MessagesTable,
			Columns: []string{chatconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatConversation.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatConversationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatConversationCreate) OnConflict(opts ...sql.ConflictOption) *ChatConversationUpsertOne {
	_c.conflict = opts
	return &ChatConversationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatConversation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatConversationCreate) OnConflictColumns(columns ...string) *ChatConversationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatConversationUpsertOne{
		create: _c,
	}
}

type (
	// ChatConversationUpsertOne is the builder for "upsert"-ing
	//  one ChatConversation node.
	ChatConversationUpsertOne struct {
		create *ChatConversationCreate
	}

	// ChatConversationUpsert is the "OnConflict" setter.
	ChatConversationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatConversationUpsert) SetUpdatedAt(v time.Time) *ChatConversationUpsert {
	u.Set(chatconversation.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateUpdatedAt() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ChatConversationUpsert) SetDeletedAt(v time.Time) *ChatConversationUpsert {
	u.Set(chatconversation.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateDeletedAt() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ChatConversationUpsert) ClearDeletedAt() *ChatConversationUpsert {
	u.SetNull(chatconversation.FieldDeletedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *ChatConversationUpsert) SetUserID(v int64) *ChatConversationUpsert {
	u.Set(chatconversation.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateUserID() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldUserID)
	return u
}

// SetTitle sets the "title" field.
func (u *ChatConversationUpsert) SetTitle(v string) *ChatConversationUpsert {
	u.Set(chatconversation.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateTitle() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldTitle)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ChatConversationUpsert) SetAPIKeyID(v int64) *ChatConversationUpsert {
	u.Set(chatconversation.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateAPIKeyID() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldAPIKeyID)
	return u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *ChatConversationUpsert) ClearAPIKeyID() *ChatConversationUpsert {
	u.SetNull(chatconversation.FieldAPIKeyID)
	return u
}

// SetModel sets the "model" field.
func (u *ChatConversationUpsert) SetModel(v string) *ChatConversationUpsert {
	u.Set(chatconversation.FieldModel, v)
	return u
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateModel() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldModel)
	return u
}

// SetSystemPrompt sets the "system_prompt" field.
func (u *ChatConversationUpsert) SetSystemPrompt(v string) *ChatConversationUpsert {
	u.Set(chatconversation.FieldSystemPrompt, v)
	return u
}

// UpdateSystemPrompt sets the "system_prompt" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateSystemPrompt() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldSystemPrompt)
	return u
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (u *ChatConversationUpsert) SetReasoningEffort(v string) *ChatConversationUpsert {
	u.Set(chatconversation.FieldReasoningEffort, v)
	return u
}

// UpdateReasoningEffort sets the "reasoning_effort" field to the value that was provided on create.
func (u *ChatConversationUpsert) UpdateReasoningEffort() *ChatConversationUpsert {
	u.SetExcluded(chatconversation.FieldReasoningEffort)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ChatConversation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatConversationUpsertOne) UpdateNewValues() *ChatConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(chatconversation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatConversation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ChatConversationUpsertOne) Ignore() *ChatConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatConversationUpsertOne) DoNothing() *ChatConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatConversationCreate.OnConflict
// documentation for more info.
func (u *ChatConversationUpsertOne) Update(set func(*ChatConversationUpsert)) *ChatConversationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatConversationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatConversationUpsertOne) SetUpdatedAt(v time.Time) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateUpdatedAt() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ChatConversationUpsertOne) SetDeletedAt(v time.Time) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateDeletedAt() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ChatConversationUpsertOne) ClearDeletedAt() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ChatConversationUpsertOne) SetUserID(v int64) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateUserID() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateUserID()
	})
}

// SetTitle sets the "title" field.
func (u *ChatConversationUpsertOne) SetTitle(v string) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateTitle() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateTitle()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ChatConversationUpsertOne) SetAPIKeyID(v int64) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateAPIKeyID() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *ChatConversationUpsertOne) ClearAPIKeyID() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetModel sets the "model" field.
func (u *ChatConversationUpsertOne) SetModel(v string) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateModel() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateModel()
	})
}

// SetSystemPrompt sets the "system_prompt" field.
func (u *ChatConversationUpsertOne) SetSystemPrompt(v string) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetSystemPrompt(v)
	})
}

// UpdateSystemPrompt sets the "system_prompt" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateSystemPrompt() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateSystemPrompt()
	})
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (u *ChatConversationUpsertOne) SetReasoningEffort(v string) *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetReasoningEffort(v)
	})
}

// UpdateReasoningEffort sets the "reasoning_effort" field to the value that was provided on create.
func (u *ChatConversationUpsertOne) UpdateReasoningEffort() *ChatConversationUpsertOne {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateReasoningEffort()
	})
}

// Exec executes the query.
func (u *ChatConversationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatConversationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatConversationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ChatConversationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ChatConversationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ChatConversationCreateBulk is the builder for creating many ChatConversation entities in bulk.
type ChatConversationCreateBulk struct {
	config
	err      error
	builders []*ChatConversationCreate
	conflict []sql.ConflictOption
}

// Save creates the ChatConversation entities in the database.
func (_c *ChatConversationCreateBulk) Save(ctx context.Context) ([]*ChatConversation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatConversation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatConversationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatConversationCreateBulk) SaveX(ctx context.Context) []*ChatConversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatConversationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatConversationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ChatConversation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ChatConversationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ChatConversationCreateBulk) OnConflict(opts ...sql.ConflictOption) *ChatConversationUpsertBulk {
	_c.conflict = opts
	return &ChatConversationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ChatConversation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ChatConversationCreateBulk) OnConflictColumns(columns ...string) *ChatConversationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ChatConversationUpsertBulk{
		create: _c,
	}
}

// ChatConversationUpsertBulk is the builder for "upsert"-ing
// a bulk of ChatConversation nodes.
type ChatConversationUpsertBulk struct {
	create *ChatConversationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ChatConversation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ChatConversationUpsertBulk) UpdateNewValues() *ChatConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(chatconversation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ChatConversation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ChatConversationUpsertBulk) Ignore() *ChatConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ChatConversationUpsertBulk) DoNothing() *ChatConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ChatConversationCreateBulk.OnConflict
// documentation for more info.
func (u *ChatConversationUpsertBulk) Update(set func(*ChatConversationUpsert)) *ChatConversationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ChatConversationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ChatConversationUpsertBulk) SetUpdatedAt(v time.Time) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateUpdatedAt() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *ChatConversationUpsertBulk) SetDeletedAt(v time.Time) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateDeletedAt() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *ChatConversationUpsertBulk) ClearDeletedAt() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.ClearDeletedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *ChatConversationUpsertBulk) SetUserID(v int64) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateUserID() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateUserID()
	})
}

// SetTitle sets the "title" field.
func (u *ChatConversationUpsertBulk) SetTitle(v string) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateTitle() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateTitle()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *ChatConversationUpsertBulk) SetAPIKeyID(v int64) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateAPIKeyID() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *ChatConversationUpsertBulk) ClearAPIKeyID() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetModel sets the "model" field.
func (u *ChatConversationUpsertBulk) SetModel(v string) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetModel(v)
	})
}

// UpdateModel sets the "model" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateModel() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateModel()
	})
}

// SetSystemPrompt sets the "system_prompt" field.
func (u *ChatConversationUpsertBulk) SetSystemPrompt(v string) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetSystemPrompt(v)
	})
}

// UpdateSystemPrompt sets the "system_prompt" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateSystemPrompt() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateSystemPrompt()
	})
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (u *ChatConversationUpsertBulk) SetReasoningEffort(v string) *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.SetReasoningEffort(v)
	})
}

// UpdateReasoningEffort sets the "reasoning_effort" field to the value that was provided on create.
func (u *ChatConversationUpsertBulk) UpdateReasoningEffort() *ChatConversationUpsertBulk {
	return u.Update(func(s *ChatConversationUpsert) {
		s.UpdateReasoningEffort()
	})
}

// Exec executes the query.
func (u *ChatConversationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ChatConversationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ChatConversationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ChatConversationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
