// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/chatconversation"
	"github.com/Wei-Shaw/sub2api/ent/chatmessage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ChatConversationUpdate is the builder for updating ChatConversation entities.
type ChatConversationUpdate struct {
	config
	hooks    []Hook
	mutation *ChatConversationMutation
}

// Where appends a list predicates to the ChatConversationUpdate builder.
func (_u *ChatConversationUpdate) Where(ps ...predicate.ChatConversation) *ChatConversationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatConversationUpdate) SetUpdatedAt(v time.Time) *ChatConversationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChatConversationUpdate) SetDeletedAt(v time.Time) *ChatConversationUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableDeletedAt(v *time.Time) *ChatConversationUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ChatConversationUpdate) ClearDeletedAt() *ChatConversationUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChatConversationUpdate) SetUserID(v int64) *ChatConversationUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableUserID(v *int64) *ChatConversationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ChatConversationUpdate) SetTitle(v string) *ChatConversationUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableTitle(v *string) *ChatConversationUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *ChatConversationUpdate) SetAPIKeyID(v int64) *ChatConversationUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableAPIKeyID(v *int64) *ChatConversationUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *ChatConversationUpdate) ClearAPIKeyID() *ChatConversationUpdate {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetModel sets the "model" field.
func (_u *ChatConversationUpdate) SetModel(v string) *ChatConversationUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableModel(v *string) *ChatConversationUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *ChatConversationUpdate) SetSystemPrompt(v string) *ChatConversationUpdate {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableSystemPrompt(v *string) *ChatConversationUpdate {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (_u *ChatConversationUpdate) SetReasoningEffort(v string) *ChatConversationUpdate {
	_u.mutation.SetReasoningEffort(v)
	return _u
}

// SetNillableReasoningEffort sets the "reasoning_effort" field if the given value is not nil.
func (_u *ChatConversationUpdate) SetNillableReasoningEffort(v *string) *ChatConversationUpdate {
	if v != nil {
		_u.SetReasoningEffort(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ChatConversationUpdate) SetUser(v *User) *ChatConversationUpdate {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *ChatConversationUpdate) SetAPIKey(v *APIKey) *ChatConversationUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the ChatMessage entity by IDs.
func (_u *ChatConversationUpdate) AddMessageIDs(ids ...int64) *ChatConversationUpdate {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the ChatMessage entity.
func (_u *ChatConversationUpdate) AddMessages(v ...*ChatMessage) *ChatConversationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the ChatConversationMutation object of the builder.
func (_u *ChatConversationUpdate) Mutation() *ChatConversationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ChatConversationUpdate) ClearUser() *ChatConversationUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *ChatConversationUpdate) ClearAPIKey() *ChatConversationUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearMessages clears all "messages" edges to the ChatMessage entity.
func (_u *ChatConversationUpdate) ClearMessages() *ChatConversationUpdate {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to ChatMessage entities by IDs.
func (_u *ChatConversationUpdate) RemoveMessageIDs(ids ...int64) *ChatConversationUpdate {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to ChatMessage entities.
func (_u *ChatConversationUpdate) RemoveMessages(v ...*ChatMessage) *ChatConversationUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChatConversationUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatConversationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChatConversationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatConversationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatConversationUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if chatconversation.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized chatconversation.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := chatconversation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatConversationUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := chatconversation.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := chatconversation.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReasoningEffort(); ok {
		if err := chatconversation.ReasoningEffortValidator(v); err != nil {
			return &ValidationError{Name: "reasoning_effort", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.reasoning_effort": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatConversation.user"`)
	}
	return nil
}

func (_u *ChatConversationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatconversation.Table, chatconversation.Columns, sqlgraph.NewFieldSpec(chatconversation.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatconversation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(chatconversation.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(chatconversation.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(chatconversation.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(chatconversation.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(chatconversation.FieldSystemPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReasoningEffort(); ok {
		_spec.SetField(chatconversation.FieldReasoningEffort, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatconversation.UserTable,
			Columns: []string{chatconversation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatconversation.UserTable,
			Columns: []string{chatconversation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatconversation.APIKeyTable,
			Columns: []string{chatconversation.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatconversation.APIKeyTable,
			Columns: []string{chatconversation.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatconversation.MessagesTable,
			Columns: []string{chatconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatconversation.MessagesTable,
			Columns: []string{chatconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatconversation.MessagesTable,
			Columns: []string{chatconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatconversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChatConversationUpdateOne is the builder for updating a single ChatConversation entity.
type ChatConversationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatConversationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatConversationUpdateOne) SetUpdatedAt(v time.Time) *ChatConversationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChatConversationUpdateOne) SetDeletedAt(v time.Time) *ChatConversationUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableDeletedAt(v *time.Time) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ChatConversationUpdateOne) ClearDeletedAt() *ChatConversationUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChatConversationUpdateOne) SetUserID(v int64) *ChatConversationUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableUserID(v *int64) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *ChatConversationUpdateOne) SetTitle(v string) *ChatConversationUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableTitle(v *string) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *ChatConversationUpdateOne) SetAPIKeyID(v int64) *ChatConversationUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableAPIKeyID(v *int64) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (_u *ChatConversationUpdateOne) ClearAPIKeyID() *ChatConversationUpdateOne {
	_u.mutation.ClearAPIKeyID()
	return _u
}

// SetModel sets the "model" field.
func (_u *ChatConversationUpdateOne) SetModel(v string) *ChatConversationUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableModel(v *string) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetSystemPrompt sets the "system_prompt" field.
func (_u *ChatConversationUpdateOne) SetSystemPrompt(v string) *ChatConversationUpdateOne {
	_u.mutation.SetSystemPrompt(v)
	return _u
}

// SetNillableSystemPrompt sets the "system_prompt" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableSystemPrompt(v *string) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetSystemPrompt(*v)
	}
	return _u
}

// SetReasoningEffort sets the "reasoning_effort" field.
func (_u *ChatConversationUpdateOne) SetReasoningEffort(v string) *ChatConversationUpdateOne {
	_u.mutation.SetReasoningEffort(v)
	return _u
}

// SetNillableReasoningEffort sets the "reasoning_effort" field if the given value is not nil.
func (_u *ChatConversationUpdateOne) SetNillableReasoningEffort(v *string) *ChatConversationUpdateOne {
	if v != nil {
		_u.SetReasoningEffort(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *ChatConversationUpdateOne) SetUser(v *User) *ChatConversationUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *ChatConversationUpdateOne) SetAPIKey(v *APIKey) *ChatConversationUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// AddMessageIDs adds the "messages" edge to the ChatMessage entity by IDs.
func (_u *ChatConversationUpdateOne) AddMessageIDs(ids ...int64) *ChatConversationUpdateOne {
	_u.mutation.AddMessageIDs(ids...)
	return _u
}

// AddMessages adds the "messages" edges to the ChatMessage entity.
func (_u *ChatConversationUpdateOne) AddMessages(v ...*ChatMessage) *ChatConversationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMessageIDs(ids...)
}

// Mutation returns the ChatConversationMutation object of the builder.
func (_u *ChatConversationUpdateOne) Mutation() *ChatConversationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ChatConversationUpdateOne) ClearUser() *ChatConversationUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *ChatConversationUpdateOne) ClearAPIKey() *ChatConversationUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearMessages clears all "messages" edges to the ChatMessage entity.
func (_u *ChatConversationUpdateOne) ClearMessages() *ChatConversationUpdateOne {
	_u.mutation.ClearMessages()
	return _u
}

// RemoveMessageIDs removes the "messages" edge to ChatMessage entities by IDs.
func (_u *ChatConversationUpdateOne) RemoveMessageIDs(ids ...int64) *ChatConversationUpdateOne {
	_u.mutation.RemoveMessageIDs(ids...)
	return _u
}

// RemoveMessages removes "messages" edges to ChatMessage entities.
func (_u *ChatConversationUpdateOne) RemoveMessages(v ...*ChatMessage) *ChatConversationUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the ChatConversationUpdate builder.
func (_u *ChatConversationUpdateOne) Where(ps ...predicate.ChatConversation) *ChatConversationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChatConversationUpdateOne) Select(field string, fields ...string) *ChatConversationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChatConversation entity.
func (_u *ChatConversationUpdateOne) Save(ctx context.Context) (*ChatConversation, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatConversationUpdateOne) SaveX(ctx context.Context) *ChatConversation {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChatConversationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatConversationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatConversationUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if chatconversation.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized chatconversation.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := chatconversation.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatConversationUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := chatconversation.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Model(); ok {
		if err := chatconversation.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReasoningEffort(); ok {
		if err := chatconversation.ReasoningEffortValidator(v); err != nil {
			return &ValidationError{Name: "reasoning_effort", err: fmt.Errorf(`ent: validator failed for field "ChatConversation.reasoning_effort": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatConversation.user"`)
	}
	return nil
}

func (_u *ChatConversationUpdateOne) sqlSave(ctx context.Context) (_node *ChatConversation, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatconversation.Table, chatconversation.Columns, sqlgraph.NewFieldSpec(chatconversation.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChatConversation.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatconversation.FieldID)
		for _, f := range fields {
			if !chatconversation.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatconversation.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatconversation.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(chatconversation.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(chatconversation.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(chatconversation.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(chatconversation.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.SystemPrompt(); ok {
		_spec.SetField(chatconversation.FieldSystemPrompt, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReasoningEffort(); ok {
		_spec.SetField(chatconversation.FieldReasoningEffort, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatconversation.UserTable,
			Columns: []string{chatconversation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatconversation.UserTable,
			Columns: []string{chatconversation.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatconversation.APIKeyTable,
			Columns: []string{chatconversation.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatconversation.APIKeyTable,
			Columns: []string{chatconversation.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatconversation.MessagesTable,
			Columns: []string{chatconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !_u.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatconversation.MessagesTable,
			Columns: []string{chatconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatconversation.MessagesTable,
			Columns: []string{chatconversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChatConversation{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatconversation.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
