// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/chatconversation"
	"github.com/Wei-Shaw/sub2api/ent/chatmessage"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// ChatMessageUpdate is the builder for updating ChatMessage entities.
type ChatMessageUpdate struct {
	config
	hooks    []Hook
	mutation *ChatMessageMutation
}

// Where appends a list predicates to the ChatMessageUpdate builder.
func (_u *ChatMessageUpdate) Where(ps ...predicate.ChatMessage) *ChatMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatMessageUpdate) SetUpdatedAt(v time.Time) *ChatMessageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *ChatMessageUpdate) SetConversationID(v int64) *ChatMessageUpdate {
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableConversationID(v *int64) *ChatMessageUpdate {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChatMessageUpdate) SetUserID(v int64) *ChatMessageUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableUserID(v *int64) *ChatMessageUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *ChatMessageUpdate) SetRole(v string) *ChatMessageUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableRole(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ChatMessageUpdate) SetContent(v string) *ChatMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableContent(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChatMessageUpdate) SetStatus(v string) *ChatMessageUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableStatus(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ChatMessageUpdate) SetErrorMessage(v string) *ChatMessageUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ChatMessageUpdate) SetNillableErrorMessage(v *string) *ChatMessageUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ChatMessageUpdate) SetMetadata(v map[string]interface{}) *ChatMessageUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ChatMessageUpdate) ClearMetadata() *ChatMessageUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// SetConversation sets the "conversation" edge to the ChatConversation entity.
func (_u *ChatMessageUpdate) SetConversation(v *ChatConversation) *ChatMessageUpdate {
	return _u.SetConversationID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *ChatMessageUpdate) SetUser(v *User) *ChatMessageUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ChatMessageMutation object of the builder.
func (_u *ChatMessageUpdate) Mutation() *ChatMessageMutation {
	return _u.mutation
}

// ClearConversation clears the "conversation" edge to the ChatConversation entity.
func (_u *ChatMessageUpdate) ClearConversation() *ChatMessageUpdate {
	_u.mutation.ClearConversation()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ChatMessageUpdate) ClearUser() *ChatMessageUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChatMessageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChatMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatMessageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chatmessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatMessageUpdate) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := chatmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := chatmessage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.status": %w`, err)}
		}
	}
	if _u.mutation.ConversationCleared() && len(_u.mutation.ConversationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMessage.conversation"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMessage.user"`)
	}
	return nil
}

func (_u *ChatMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatmessage.Table, chatmessage.Columns, sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatmessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(chatmessage.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(chatmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(chatmessage.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(chatmessage.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(chatmessage.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(chatmessage.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.ConversationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.ConversationTable,
			Columns: []string{chatmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatconversation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.ConversationTable,
			Columns: []string{chatmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatconversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.UserTable,
			Columns: []string{chatmessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.UserTable,
			Columns: []string{chatmessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChatMessageUpdateOne is the builder for updating a single ChatMessage entity.
type ChatMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatMessageMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatMessageUpdateOne) SetUpdatedAt(v time.Time) *ChatMessageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *ChatMessageUpdateOne) SetConversationID(v int64) *ChatMessageUpdateOne {
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableConversationID(v *int64) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChatMessageUpdateOne) SetUserID(v int64) *ChatMessageUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableUserID(v *int64) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *ChatMessageUpdateOne) SetRole(v string) *ChatMessageUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableRole(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ChatMessageUpdateOne) SetContent(v string) *ChatMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableContent(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ChatMessageUpdateOne) SetStatus(v string) *ChatMessageUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableStatus(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *ChatMessageUpdateOne) SetErrorMessage(v string) *ChatMessageUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *ChatMessageUpdateOne) SetNillableErrorMessage(v *string) *ChatMessageUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *ChatMessageUpdateOne) SetMetadata(v map[string]interface{}) *ChatMessageUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *ChatMessageUpdateOne) ClearMetadata() *ChatMessageUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// SetConversation sets the "conversation" edge to the ChatConversation entity.
func (_u *ChatMessageUpdateOne) SetConversation(v *ChatConversation) *ChatMessageUpdateOne {
	return _u.SetConversationID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *ChatMessageUpdateOne) SetUser(v *User) *ChatMessageUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ChatMessageMutation object of the builder.
func (_u *ChatMessageUpdateOne) Mutation() *ChatMessageMutation {
	return _u.mutation
}

// ClearConversation clears the "conversation" edge to the ChatConversation entity.
func (_u *ChatMessageUpdateOne) ClearConversation() *ChatMessageUpdateOne {
	_u.mutation.ClearConversation()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ChatMessageUpdateOne) ClearUser() *ChatMessageUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ChatMessageUpdate builder.
func (_u *ChatMessageUpdateOne) Where(ps ...predicate.ChatMessage) *ChatMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChatMessageUpdateOne) Select(field string, fields ...string) *ChatMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChatMessage entity.
func (_u *ChatMessageUpdateOne) Save(ctx context.Context) (*ChatMessage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatMessageUpdateOne) SaveX(ctx context.Context) *ChatMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChatMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatMessageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := chatmessage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatMessageUpdateOne) check() error {
	if v, ok := _u.mutation.Role(); ok {
		if err := chatmessage.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := chatmessage.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ChatMessage.status": %w`, err)}
		}
	}
	if _u.mutation.ConversationCleared() && len(_u.mutation.ConversationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMessage.conversation"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMessage.user"`)
	}
	return nil
}

func (_u *ChatMessageUpdateOne) sqlSave(ctx context.Context) (_node *ChatMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatmessage.Table, chatmessage.Columns, sqlgraph.NewFieldSpec(chatmessage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChatMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatmessage.FieldID)
		for _, f := range fields {
			if !chatmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatmessage.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(chatmessage.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(chatmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(chatmessage.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(chatmessage.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(chatmessage.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(chatmessage.FieldMetadata, field.TypeJSON)
	}
	if _u.mutation.ConversationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.ConversationTable,
			Columns: []string{chatmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatconversation.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.ConversationTable,
			Columns: []string{chatmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatconversation.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.UserTable,
			Columns: []string{chatmessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessage.UserTable,
			Columns: []string{chatmessage.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChatMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
